# Download iDFlakies

In [ ]:
!git clone https://github.com/UT-SE-Research/iDFlakies.git
%cd iDFlakies

Cloning into 'iDFlakies'...
remote: Enumerating objects: 5797, done.
remote: Counting objects: 100% (564/564), done.
remote: Compressing objects: 100% (203/203), done.
remote: Total 5797 (delta 466), reused 362 (delta 361), pack-reused 5233 (from 3)
Receiving objects: 100% (5797/5797), 1.26 MiB | 9.58 MiB/s, done.
Resolving deltas: 100% (1437/1437), done.
/content/iDFlakies

In [ ]:
!ls

deploy.log	idflakies-legacy	pom.xml		  README.md
gradle-modify	idflakies-maven-plugin	README-deploy.md  scripts
idflakies-core	pom-modify		README-gradle.md

In [ ]:
# Look for csv or json files
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith((".csv", ".json")):
            print(os.path.join(root, file))

./scripts/idfProjectsFixer.csv
./scripts/idfProjects4.csv
./scripts/idfProjects3.csv
./scripts/idfProjectsMinimizer.csv
./scripts/idfProjects2.csv
./scripts/idfProjects1.csv
./scripts/testExpectations.csv
./scripts/docker/icst-dataset/extended-individual-split/kpavlov.jreactive-8583.csv
./scripts/docker/icst-dataset/extended-individual-split/graphaware.neo4j-uuid.csv
./scripts/docker/icst-dataset/extended-individual-split/threerings.clyde.csv
./scripts/docker/icst-dataset/extended-individual-split/nurtak.objectgraphvisualization.csv
./scripts/docker/icst-dataset/extended-individual-split/wso2.balana.csv
./scripts/docker/icst-dataset/extended-individual-split/playframework.netty-reactive-streams.csv
./scripts/docker/icst-dataset/extended-individual-split/faustxvi.junit5-docker.csv
./scripts/docker/icst-dataset/extended-individual-split/iotaledger.iota-java.csv
./scripts/docker/icst-dataset/extended-individual-split/dschanoeh.kayak.csv
./scripts/docker/icst-dataset/extended-individual-split/openzipkin.zipkin-finagle.csv
./scripts/docker/icst-dataset/extended-individual-split/learnk8s.spring-boot-k8s-hpa.csv
./scripts/docker/icst-dataset/extended-individual-split/microsoft.java-debug.csv
./scripts/docker/icst-dataset/extended-individual-split/jutzig.github-release-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/xuxueli.xxl-sso.csv
./scripts/docker/icst-dataset/extended-individual-split/nationalsecurityagency.timely.csv
./scripts/docker/icst-dataset/extended-individual-split/droidefense.engine.csv
./scripts/docker/icst-dataset/extended-individual-split/zavtech.morpheus-core.csv
./scripts/docker/icst-dataset/extended-individual-split/fluent.fluent-logger-java.csv
./scripts/docker/icst-dataset/extended-individual-split/exrick.xpay.csv
./scripts/docker/icst-dataset/extended-individual-split/gooddata.gooddata-cl.csv
./scripts/docker/icst-dataset/extended-individual-split/xcesco.kripton.csv
./scripts/docker/icst-dataset/extended-individual-split/spotify.folsom.csv
./scripts/docker/icst-dataset/extended-individual-split/adobe.s3mock.csv
./scripts/docker/icst-dataset/extended-individual-split/phax.as2-lib.csv
./scripts/docker/icst-dataset/extended-individual-split/rrd4j.rrd4j.csv
./scripts/docker/icst-dataset/extended-individual-split/blazemeter.jmeter-bzm-plugins.csv
./scripts/docker/icst-dataset/extended-individual-split/spring-petclinic.spring-petclinic-microservices.csv
./scripts/docker/icst-dataset/extended-individual-split/openhft.chronicle-engine.csv
./scripts/docker/icst-dataset/extended-individual-split/bujiio.buji-pac4j.csv
./scripts/docker/icst-dataset/extended-individual-split/spotify.dbeam.csv
./scripts/docker/icst-dataset/extended-individual-split/vbauer.houdini.csv
./scripts/docker/icst-dataset/extended-individual-split/softwareking.halo.csv
./scripts/docker/icst-dataset/extended-individual-split/xenv.s-mall-ssm.csv
./scripts/docker/icst-dataset/extended-individual-split/tzaeschke.ode4j.csv
./scripts/docker/icst-dataset/extended-individual-split/jenkinsci.credentials-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/jhipster.jhipster-registry.csv
./scripts/docker/icst-dataset/extended-individual-split/shred.acme4j.csv
./scripts/docker/icst-dataset/extended-individual-split/ozimov.spring-boot-email-tools.csv
./scripts/docker/icst-dataset/extended-individual-split/googlecloudplatform.dataflowtemplates.csv
./scripts/docker/icst-dataset/extended-individual-split/luisgoncalves.xades4j.csv
./scripts/docker/icst-dataset/extended-individual-split/opencypher.opencypher.csv
./scripts/docker/icst-dataset/extended-individual-split/hyperledger.quilt.csv
./scripts/docker/icst-dataset/extended-individual-split/kengotoda.what-is-maven.csv
./scripts/docker/icst-dataset/extended-individual-split/charithe.kafka-junit.csv
./scripts/docker/icst-dataset/extended-individual-split/wikimedia.search-highlighter.csv
./scripts/docker/icst-dataset/extended-individual-split/kongzhidea.netty4-rpc.csv
./scripts/docker/icst-dataset/extended-individual-split/mobivm.robovm.csv
./scripts/docker/icst-dataset/extended-individual-split/danielolszewski.blog.csv
./scripts/docker/icst-dataset/extended-individual-split/digitalfondue.lavagna.csv
./scripts/docker/icst-dataset/extended-individual-split/dnsjava.dnsjava.csv
./scripts/docker/icst-dataset/extended-individual-split/plutext.docx4j-importxhtml.csv
./scripts/docker/icst-dataset/extended-individual-split/vbauer.herald.csv
./scripts/docker/icst-dataset/extended-individual-split/vert-x3.vertx-rabbitmq-client.csv
./scripts/docker/icst-dataset/extended-individual-split/ict-bda.easyml.csv
./scripts/docker/icst-dataset/extended-individual-split/crosg.albianj2.csv
./scripts/docker/icst-dataset/extended-individual-split/googleapis.google-auth-library-java.csv
./scripts/docker/icst-dataset/extended-individual-split/hexagonframework.spring-data-ebean.csv
./scripts/docker/icst-dataset/extended-individual-split/itfsw.mybatis-generator-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/ihtsdo.snomed-in-5-minutes.csv
./scripts/docker/icst-dataset/extended-individual-split/aerisnju.mylizzie.csv
./scripts/docker/icst-dataset/extended-individual-split/sonarsource.sonar-scanner-cli.csv
./scripts/docker/icst-dataset/extended-individual-split/talsma-ict.umldoclet.csv
./scripts/docker/icst-dataset/extended-individual-split/reficio.p2-maven-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/fromage.redpipe.csv
./scripts/docker/icst-dataset/extended-individual-split/hsiafan.requests.csv
./scripts/docker/icst-dataset/extended-individual-split/bitrich-info.xchange-stream.csv
./scripts/docker/icst-dataset/extended-individual-split/sonatype-nexus-community.nexus-repository-helm.csv
./scripts/docker/icst-dataset/extended-individual-split/sonatype-nexus-community.nexus-repository-composer.csv
./scripts/docker/icst-dataset/extended-individual-split/snowxwolf.boot.csv
./scripts/docker/icst-dataset/extended-individual-split/square.osstrich.csv
./scripts/docker/icst-dataset/extended-individual-split/kylelnicholls.parameterized-builds.csv
./scripts/docker/icst-dataset/extended-individual-split/pingao777.markdown-preview-sync.csv
./scripts/docker/icst-dataset/extended-individual-split/xiaolyuh.layering-cache.csv
./scripts/docker/icst-dataset/extended-individual-split/tongxiji.shadowsocks-java.csv
./scripts/docker/icst-dataset/extended-individual-split/lipiji.jrnn.csv
./scripts/docker/icst-dataset/extended-individual-split/itzsomebody.radon.csv
./scripts/docker/icst-dataset/extended-individual-split/wikidata.wikidata-toolkit.csv
./scripts/docker/icst-dataset/extended-individual-split/plivo.plivo-java.csv
./scripts/docker/icst-dataset/extended-individual-split/espertechinc.esper.csv
./scripts/docker/icst-dataset/extended-individual-split/hubspot.rosetta.csv
./scripts/docker/icst-dataset/extended-individual-split/kiegroup.droolsjbpm-tools.csv
./scripts/docker/icst-dataset/extended-individual-split/daggerok.streaming-file-server.csv
./scripts/docker/icst-dataset/extended-individual-split/elennick.retry4j.csv
./scripts/docker/icst-dataset/extended-individual-split/fasterxml.jackson-dataformats-text.csv
./scripts/docker/icst-dataset/extended-individual-split/aeshell.aesh.csv
./scripts/docker/icst-dataset/extended-individual-split/vert-x3.vertx-service-proxy.csv
./scripts/docker/icst-dataset/extended-individual-split/eclipse.egit-github.csv
./scripts/docker/icst-dataset/extended-individual-split/amadeusitgroup.sonar-stash.csv
./scripts/docker/icst-dataset/extended-individual-split/webrtc.kite.csv
./scripts/docker/icst-dataset/extended-individual-split/jenkinsci.kubernetes-pipeline-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/vert-x3.vertx-stack.csv
./scripts/docker/icst-dataset/extended-individual-split/netsoss.headless-burp.csv
./scripts/docker/icst-dataset/extended-individual-split/vert-x3.vertx-redis-client.csv
./scripts/docker/icst-dataset/extended-individual-split/consulo.consulo-csharp.csv
./scripts/docker/icst-dataset/extended-individual-split/jenkinsci.bitbucket-build-status-notifier-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/mapr-demos.finserv-application-blueprint.csv
./scripts/docker/icst-dataset/extended-individual-split/waikato.meka.csv
./scripts/docker/icst-dataset/extended-individual-split/ottogroup.flink-spector.csv
./scripts/docker/icst-dataset/extended-individual-split/authorjapps.zerocode.csv
./scripts/docker/icst-dataset/extended-individual-split/braintree.braintree_java.csv
./scripts/docker/icst-dataset/extended-individual-split/influxdata.influxdb-java.csv
./scripts/docker/icst-dataset/extended-individual-split/chaokunyang.jkes.csv
./scripts/docker/icst-dataset/extended-individual-split/nationalsecurityagency.emissary.csv
./scripts/docker/icst-dataset/extended-individual-split/haoxiaoyong1014.springboot-examples.csv
./scripts/docker/icst-dataset/extended-individual-split/rakam-io.rakam.csv
./scripts/docker/icst-dataset/extended-individual-split/eclipse-ee4j.yasson.csv
./scripts/docker/icst-dataset/extended-individual-split/wojciechzankowski.iextrading4j.csv
./scripts/docker/icst-dataset/extended-individual-split/vt-middleware.passay.csv
./scripts/docker/icst-dataset/extended-individual-split/apache.commons-compress.csv
./scripts/docker/icst-dataset/extended-individual-split/joel-costigliola.assertj-swing.csv
./scripts/docker/icst-dataset/extended-individual-split/nidi3.graphviz-java.csv
./scripts/docker/icst-dataset/extended-individual-split/petitparser.java-petitparser.csv
./scripts/docker/icst-dataset/extended-individual-split/cjbi.wetech-admin.csv
./scripts/docker/icst-dataset/extended-individual-split/jboss-modules.jboss-modules.csv
./scripts/docker/icst-dataset/extended-individual-split/danielflower.maven-gitlog-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/cognifide.aem-rules-for-sonarqube.csv
./scripts/docker/icst-dataset/extended-individual-split/codahale.usl4j.csv
./scripts/docker/icst-dataset/extended-individual-split/danielnorberg.auto-matter.csv
./scripts/docker/icst-dataset/extended-individual-split/microsoft.spring-data-gremlin.csv
./scripts/docker/icst-dataset/extended-individual-split/javaee.grizzly.csv
./scripts/docker/icst-dataset/extended-individual-split/microsoft.git-credential-manager-for-mac-and-linux.csv
./scripts/docker/icst-dataset/extended-individual-split/apache.nifi-registry.csv
./scripts/docker/icst-dataset/extended-individual-split/yahoo.sherlock.csv
./scripts/docker/icst-dataset/extended-individual-split/spotbugs.sonar-findbugs.csv
./scripts/docker/icst-dataset/extended-individual-split/kodapan.osm-common.csv
./scripts/docker/icst-dataset/extended-individual-split/xmlet.htmlflow.csv
./scripts/docker/icst-dataset/extended-individual-split/spinn3r.noxy.csv
./scripts/docker/icst-dataset/extended-individual-split/latexdraw.latexdraw.csv
./scripts/docker/icst-dataset/extended-individual-split/jpmml.jpmml-model.csv
./scripts/docker/icst-dataset/extended-individual-split/spring-projects.spring-guice.csv
./scripts/docker/icst-dataset/extended-individual-split/ralscha.extdirectspring.csv
./scripts/docker/icst-dataset/extended-individual-split/qwazer.scheme2ddl.csv
./scripts/docker/icst-dataset/extended-individual-split/duydo.elasticsearch-analysis-vietnamese.csv
./scripts/docker/icst-dataset/extended-individual-split/confluentinc.kafka-connect-storage-cloud.csv
./scripts/docker/icst-dataset/extended-individual-split/baidu.uid-generator.csv
./scripts/docker/icst-dataset/extended-individual-split/fasterxml.jackson-datatype-joda.csv
./scripts/docker/icst-dataset/extended-individual-split/ctco.cukes.csv
./scripts/docker/icst-dataset/extended-individual-split/elimirren.vx-api-gateway.csv
./scripts/docker/icst-dataset/extended-individual-split/goxr3plus.xr3player.csv
./scripts/docker/icst-dataset/extended-individual-split/msemys.esjc.csv
./scripts/docker/icst-dataset/extended-individual-split/dempsy.dempsy.csv
./scripts/docker/icst-dataset/extended-individual-split/giltene.jhiccup.csv
./scripts/docker/icst-dataset/extended-individual-split/petegoo.tcslackbuildnotifier.csv
./scripts/docker/icst-dataset/extended-individual-split/jenkinsci.dashboard-view-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/openadv.gae.csv
./scripts/docker/icst-dataset/extended-individual-split/joshlong.bootiful-reactive-microservices.csv
./scripts/docker/icst-dataset/extended-individual-split/drombler.drombler-fx.csv
./scripts/docker/icst-dataset/extended-individual-split/openhft.java-thread-affinity.csv
./scripts/docker/icst-dataset/extended-individual-split/apache.sis.csv
./scripts/docker/icst-dataset/extended-individual-split/cloudfoundry.java-buildpack-auto-reconfiguration.csv
./scripts/docker/icst-dataset/extended-individual-split/javolution.javolution.csv
./scripts/docker/icst-dataset/extended-individual-split/hagyao520.appium.csv
./scripts/docker/icst-dataset/extended-individual-split/gbif.ipt.csv
./scripts/docker/icst-dataset/extended-individual-split/opentelecoms-org.jsmpp.csv
./scripts/docker/icst-dataset/extended-individual-split/wuyouzhuguli.febs-security.csv
./scripts/docker/icst-dataset/extended-individual-split/arangodb-community.arangodb-tinkerpop-provider.csv
./scripts/docker/icst-dataset/extended-individual-split/robinst.autolink-java.csv
./scripts/docker/icst-dataset/extended-individual-split/jenkinsci.maven-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/vert-x3.vertx-hazelcast.csv
./scripts/docker/icst-dataset/extended-individual-split/jbox2d.jbox2d.csv
./scripts/docker/icst-dataset/extended-individual-split/jenkinsci.workflow-cps-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/zalando.problem.csv
./scripts/docker/icst-dataset/extended-individual-split/rongcloud.server-sdk-java.csv
./scripts/docker/icst-dataset/extended-individual-split/goxr3plus.javafx-web-browser.csv
./scripts/docker/icst-dataset/extended-individual-split/jenkinsci.docker-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/michael-simons.biking2.csv
./scripts/docker/icst-dataset/extended-individual-split/bells.elasticsearch-analysis-dynamic-synonym.csv
./scripts/docker/icst-dataset/extended-individual-split/itext.itextpdf.csv
./scripts/docker/icst-dataset/extended-individual-split/jidesoft.jide-oss.csv
./scripts/docker/icst-dataset/extended-individual-split/tomitribe.crest.csv
./scripts/docker/icst-dataset/extended-individual-split/eclipse.eclipse-collections-kata.csv
./scripts/docker/icst-dataset/extended-individual-split/robo-code.robocode.csv
./scripts/docker/icst-dataset/extended-individual-split/lionsoul2014.jcseg.csv
./scripts/docker/icst-dataset/extended-individual-split/membrane.service-proxy.csv
./scripts/docker/icst-dataset/extended-individual-split/errai.errai-tutorial.csv
./scripts/docker/icst-dataset/extended-individual-split/jzyong.mmo-server.csv
./scripts/docker/icst-dataset/extended-individual-split/ehcache.sizeof.csv
./scripts/docker/icst-dataset/extended-individual-split/opencog.relex.csv
./scripts/docker/icst-dataset/extended-individual-split/spring-projects.spring-ws.csv
./scripts/docker/icst-dataset/extended-individual-split/creactiviti.piper.csv
./scripts/docker/icst-dataset/extended-individual-split/hipparchus-math.hipparchus.csv
./scripts/docker/icst-dataset/extended-individual-split/spring-projects.spring-retry.csv
./scripts/docker/icst-dataset/extended-individual-split/koraktor.mavanagaiata.csv
./scripts/docker/icst-dataset/extended-individual-split/intuit.benten.csv
./scripts/docker/icst-dataset/extended-individual-split/bridata.dbus.csv
./scripts/docker/icst-dataset/extended-individual-split/hazelcast.spring-data-hazelcast.csv
./scripts/docker/icst-dataset/extended-individual-split/julietkilo.canbabel.csv
./scripts/docker/icst-dataset/extended-individual-split/dieselpoint.norm.csv
./scripts/docker/icst-dataset/extended-individual-split/lior-k.fast-elasticsearch-vector-scoring.csv
./scripts/docker/icst-dataset/extended-individual-split/confluentinc.rest-utils.csv
./scripts/docker/icst-dataset/extended-individual-split/merck.halyard.csv
./scripts/docker/icst-dataset/extended-individual-split/docker-java.docker-java.csv
./scripts/docker/icst-dataset/extended-individual-split/dadoonet.fscrawler.csv
./scripts/docker/icst-dataset/extended-individual-split/talend.components.csv
./scripts/docker/icst-dataset/extended-individual-split/lambda-3.graphene.csv
./scripts/docker/icst-dataset/extended-individual-split/sudavideo.myvideoapi.csv
./scripts/docker/icst-dataset/extended-individual-split/jenkinsci.cucumber-reports-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/smoketurner.dropwizard-consul.csv
./scripts/docker/icst-dataset/extended-individual-split/dataartisans.flink-training-exercises.csv
./scripts/docker/icst-dataset/extended-individual-split/vbauer.jackdaw.csv
./scripts/docker/icst-dataset/extended-individual-split/ktuukkan.marine-api.csv
./scripts/docker/icst-dataset/extended-individual-split/jetty-project.jetty-alpn.csv
./scripts/docker/icst-dataset/extended-individual-split/moshowgame.springbootcodegenerator.csv
./scripts/docker/icst-dataset/extended-individual-split/easymock.easymock.csv
./scripts/docker/icst-dataset/extended-individual-split/wuyouzhuguli.febs-shiro.csv
./scripts/docker/icst-dataset/extended-individual-split/armenak.datadefender.csv
./scripts/docker/icst-dataset/extended-individual-split/spring-projects.spring-data-envers.csv
./scripts/docker/icst-dataset/extended-individual-split/magro.memcached-session-manager.csv
./scripts/docker/icst-dataset/extended-individual-split/mbechler.marshalsec.csv
./scripts/docker/icst-dataset/extended-individual-split/3breadt.dd-plist.csv
./scripts/docker/icst-dataset/extended-individual-split/javadelight.delight-nashorn-sandbox.csv
./scripts/docker/icst-dataset/extended-individual-split/deegree.deegree3.csv
./scripts/docker/icst-dataset/extended-individual-split/vackosar.gitflow-incremental-builder.csv
./scripts/docker/icst-dataset/extended-individual-split/alipay.sofa-ark.csv
./scripts/docker/icst-dataset/extended-individual-split/signalapp.signal-server.csv
./scripts/docker/icst-dataset/extended-individual-split/kaiwaehner.kafka-streams-machine-learning-examples.csv
./scripts/docker/icst-dataset/extended-individual-split/powertac.powertac-server.csv
./scripts/docker/icst-dataset/extended-individual-split/logzio.sawmill.csv
./scripts/docker/icst-dataset/extended-individual-split/lukaszlenart.launch4j-maven-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/vbauer.caesar.csv
./scripts/docker/icst-dataset/extended-individual-split/ppiastucki.recast4j.csv
./scripts/docker/icst-dataset/extended-individual-split/technionyp5779.team4.csv
./scripts/docker/icst-dataset/extended-individual-split/spring-projects.spring-amqp-samples.csv
./scripts/docker/icst-dataset/extended-individual-split/hzwy23.batch-scheduler.csv
./scripts/docker/icst-dataset/extended-individual-split/apache.commons-pool.csv
./scripts/docker/icst-dataset/extended-individual-split/kostyasha.yet-another-docker-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/pyvesb.advancedachievements.csv
./scripts/docker/icst-dataset/extended-individual-split/wildfly.wildfly-maven-plugin.csv
./scripts/docker/icst-dataset/extended-individual-split/seagull1985.luckyframeweb.csv
./scripts/docker/icst-dataset/extended-individual-split/codingchili.excelastic.csv
./scripts/docker/icst-dataset/extended-individual-split/blackmoden.iclouddisk.csv
./scripts/docker/icst-dataset/extended-individual-split/awhitford.lombok.maven.csv
./scripts/docker/icst-dataset/extended-individual-split/openhft.chronicle-threads.csv
./scripts/docker/icst-dataset/extended-individual-split/pig4cloud.pig.csv
./scripts/docker/icst-dataset/extended-individual-split/zalando.jackson-datatype-money.csv
./scripts/docker/icst-dataset/extended-individual-split/leonchen83.redis-replicator.csv

README.md states -- To see all of the flaky tests detected by iDFlakies one can refer simply to the scripts/docker/all-output/kevinsawicki.http-request_output/all_flaky_tests_list.csv file. The file lists all the flaky tests detected for each round of each configuration

In [ ]:
import glob #python library that helps you find and match patterns

flaky_lists = glob.glob(
    "./**/all_flaky_tests_list.csv",
    recursive=True
)

print("Flaky result CSVs:", len(flaky_lists))
print(flaky_lists[:10])

Flaky result CSVs: 0
[]

In [ ]:
import os

print(os.getcwd())

/content/iDFlakies

In [ ]:
!ls scripts/docker

augDockerfile		   data		      run-project-pool.sh
baseDockerfile		   icst-dataset       run_project.sh
build_docker_image.sh	   individual-split   toolingDockerfile
cleanimages.sh		   module-key	      update.sh
create_and_run_dockers.sh  run_experiment.sh
create_dockerfile.sh	   run-pool.sh

## Check if all-output exists without running

In [ ]:
print(os.path.exists("scripts/docker/all-output"))

False

Repo has inputs and artifacts, but the all_flaky_tests_lists.csv file that consists of flaky-test summary is only generated during execution and no included by default

In [ ]:
!find scripts/docker/icst-dataset -maxdepth 2 -type f | head -30

scripts/docker/icst-dataset/extended-individual-split/kpavlov.jreactive-8583.csv
scripts/docker/icst-dataset/extended-individual-split/graphaware.neo4j-uuid.csv
scripts/docker/icst-dataset/extended-individual-split/threerings.clyde.csv
scripts/docker/icst-dataset/extended-individual-split/nurtak.objectgraphvisualization.csv
scripts/docker/icst-dataset/extended-individual-split/wso2.balana.csv
scripts/docker/icst-dataset/extended-individual-split/playframework.netty-reactive-streams.csv
scripts/docker/icst-dataset/extended-individual-split/faustxvi.junit5-docker.csv
scripts/docker/icst-dataset/extended-individual-split/iotaledger.iota-java.csv
scripts/docker/icst-dataset/extended-individual-split/dschanoeh.kayak.csv
scripts/docker/icst-dataset/extended-individual-split/openzipkin.zipkin-finagle.csv
scripts/docker/icst-dataset/extended-individual-split/learnk8s.spring-boot-k8s-hpa.csv
scripts/docker/icst-dataset/extended-individual-split/microsoft.java-debug.csv
scripts/docker/icst-dataset/extended-individual-split/jutzig.github-release-plugin.csv
scripts/docker/icst-dataset/extended-individual-split/xuxueli.xxl-sso.csv
scripts/docker/icst-dataset/extended-individual-split/nationalsecurityagency.timely.csv
scripts/docker/icst-dataset/extended-individual-split/droidefense.engine.csv
scripts/docker/icst-dataset/extended-individual-split/zavtech.morpheus-core.csv
scripts/docker/icst-dataset/extended-individual-split/fluent.fluent-logger-java.csv
scripts/docker/icst-dataset/extended-individual-split/exrick.xpay.csv
scripts/docker/icst-dataset/extended-individual-split/gooddata.gooddata-cl.csv
scripts/docker/icst-dataset/extended-individual-split/xcesco.kripton.csv
scripts/docker/icst-dataset/extended-individual-split/spotify.folsom.csv
scripts/docker/icst-dataset/extended-individual-split/adobe.s3mock.csv
scripts/docker/icst-dataset/extended-individual-split/phax.as2-lib.csv
scripts/docker/icst-dataset/extended-individual-split/rrd4j.rrd4j.csv
scripts/docker/icst-dataset/extended-individual-split/blazemeter.jmeter-bzm-plugins.csv
scripts/docker/icst-dataset/extended-individual-split/spring-petclinic.spring-petclinic-microservices.csv
scripts/docker/icst-dataset/extended-individual-split/openhft.chronicle-engine.csv
scripts/docker/icst-dataset/extended-individual-split/bujiio.buji-pac4j.csv
scripts/docker/icst-dataset/extended-individual-split/spotify.dbeam.csv

In [ ]:
!find scripts/docker/icst-dataset -iname "*http-request*"

scripts/docker/icst-dataset/comprehensive-individual-split/kevinsawicki.http-request.csv

In [ ]:
import pandas as pd

path = "scripts/docker/icst-dataset/comprehensive-individual-split/kevinsawicki.http-request.csv"

df = pd.read_csv(path)

print(df.shape)
print(df.columns)
df.head()

(0, 2)
Index(['https://github.com/kevinsawicki/http-request', '2d62a3e9da726942a93cf16b6e91c0187e6c0136'], dtype='object')

Empty DataFrame
Columns: [https://github.com/kevinsawicki/http-request, 2d62a3e9da726942a93cf16b6e91c0187e6c0136]
Index: []

Shows that previous has no headers, so try again without header

In [ ]:
df = pd.read_csv(
    path,
    header=None,
    names=["github_url", "commit_sha"])
df

,github_url,commit_sha
0,https://github.com/kevinsawicki/http-request,2d62a3e9da726942a93cf16b6e91c0187e6c0136

In [ ]:
print(df.shape)

(1, 2)

Files in the icst-dataset are the inputs for the dataset. The csv files contain the github_url and commit_sha. They do not contain flaky-test features or labels that we require for flaky-tests.

In [ ]:

import json

dependency_files = glob.glob(
    "./scripts/minimized-files/**/*dependencies.json",
    recursive=True
)

print("Dependency files count:", len(dependency_files))
print(dependency_files[:10])

Dependency files count: 6
['./scripts/minimized-files/naming/org.jboss.as.naming.WritableServiceBasedNamingStoreTestCase.testPermissions-c494a241f11c551779bc1904fa47348e-PASS-dependencies.json', './scripts/minimized-files/cukes-http/lv.ctco.cukes.http.facade.HttpAssertionFacadeImplTest.shouldReturnBodyWhenEnabledAndNoMax-8cbc2d89d81d400bd1c61381f60a426a-FAILURE-dependencies.json', './scripts/minimized-files/marine-api/net.sf.marineapi.ais.parser.AISMessageFactoryTest.testCreateWithTwo-64e87f61fe0dc7194d0c8be1eb266d7f-ERROR-dependencies.json', './scripts/minimized-files/marine-api/net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testSequenceListenerWithIncorrectOrder-10be918b1171de27588c31d9a89823cd-ERROR-dependencies.json', './scripts/minimized-files/elastic-job-lite-core/io.elasticjob.lite.internal.instance.ShutdownListenerManagerTest.assertIsShutdownAlready-f3c196681eb02fe87d6f88b4ff609ea7-ERROR-dependencies.json', './scripts/minimized-files/lib/com.github.kevinsawicki.http.HttpRequestTest.postWithVaragsQueryParams-b9ce25cb22a453860a16b1588b971ca1-ERROR-dependencies.json']

## Check what is in a dependency file

In [ ]:
first_path = dependency_files[0]

with open(first_path, "r") as f:
    data = json.load(f)

print("File path for first dependency:", first_path)
print("Type:", type(data))
print(data)

File path for first dependency: ./scripts/minimized-files/naming/org.jboss.as.naming.WritableServiceBasedNamingStoreTestCase.testPermissions-c494a241f11c551779bc1904fa47348e-PASS-dependencies.json
Type: <class 'dict'>

In [ ]:
# For easier analysis of the data
print("Data keys: ", data.keys())

Data keys:  dict_keys(['time', 'expectedRun', 'expected', 'dependentTest', 'polluters', 'hash', 'flakyClass'])

## Check the values in each feature

In [ ]:
print("Time:", data["time"])
print("Expected Run:", data["expectedRun"])
print("Expected:", data["expected"])
print("Dependent Test:", data["dependentTest"])
print("Polluters:", data["polluters"])
print("Hash:", data["hash"])
print("Flaky Class:", data["flakyClass"])

Time: {'startTime': 1716586758119, 'endTime': 1716587141597, 'elapsedSeconds': 383.4779999256134}

- OD means order-dependent flaky test.
- testOrder gives us the order of how we should be running the test.
- dependentTest is what we are investigating to see if it is flaky.

## Check the fields in expectedRun and Polluters

In [ ]:
print("Expected Run fields:", data["expectedRun"].keys())
print("Polluters fields:", data["polluters"][0].keys())

Expected Run fields: dict_keys(['id', 'testOrder', 'results'])
Polluters fields: dict_keys(['time', 'index', 'deps', 'cleanerData'])

In [ ]:
print(data["polluters"][0]["cleanerData"].keys())

dict_keys(['dependentTest', 'time', 'expected', 'isolationResult', 'cleaners'])

polluters give us more detail into what tests may change this behavior. (in this situation, it is testBindNested)

In [ ]:
data["expectedRun"]["testOrder"]

['org.jboss.as.naming.ExternalContextsNavigableSetTestCase.testGetParentContext',
 'org.jboss.as.naming.InitialContextFactoryTestCase.testInitialFactory',
 'org.jboss.as.naming.InitialContextFactoryTestCase.testJavaContext',
 'org.jboss.as.naming.InitialContextTestCase.testRegisterURLSchemeHandler',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testListBindingsNameNotFound',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testUnbindNotFound',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testListBindings',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testList',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testAutoRemove',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testBindAndLookup',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testBindAndRebind',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testBindUnbindLookup',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testListNameNotFound',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testRebindEmptyName',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testLookupNameNotFound',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testRebindInvalidContext',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testBindAndLookupResolveResult',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testRebindAndLookup',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testBindEmptyName',
 'org.jboss.as.naming.InMemoryNamingStoreTestCase.testLookupEmptyName',
 'org.jboss.as.naming.NamingContextTestCase.testRebindReferenceable',
 'org.jboss.as.naming.NamingContextTestCase.testLookupReference',
 'org.jboss.as.naming.NamingContextTestCase.testCreateSubcontext',
 'org.jboss.as.naming.NamingContextTestCase.testListBindingsNameNotFound',
 'org.jboss.as.naming.NamingContextTestCase.testLookupWitResolveResult',
 'org.jboss.as.naming.NamingContextTestCase.testListBindings',
 'org.jboss.as.naming.NamingContextTestCase.testBind',
 'org.jboss.as.naming.NamingContextTestCase.testList',
 'org.jboss.as.naming.NamingContextTestCase.testListNameNotFound',
 'org.jboss.as.naming.NamingContextTestCase.testLookupNameNotFound',
 'org.jboss.as.naming.NamingContextTestCase.testLookupLink',
 'org.jboss.as.naming.NamingContextTestCase.testListBindingsWithContinuation',
 'org.jboss.as.naming.NamingContextTestCase.testListWithContinuation',
 'org.jboss.as.naming.NamingContextTestCase.testBindReferenceable',
 'org.jboss.as.naming.NamingContextTestCase.testLookup',
 'org.jboss.as.naming.NamingContextTestCase.testLookupWithContinuation',
 'org.jboss.as.naming.NamingContextTestCase.testRebind',
 'org.jboss.as.naming.NamingContextTestCase.testLookupContextLink',
 'org.jboss.as.naming.NamingContextTestCase.testUnbind',
 'org.jboss.as.naming.NamingContextTestCase.testLookupEmptyName',
 'org.jboss.as.naming.NamingEventCoordinatorTestCase.testFireSubTreeEvent',
 'org.jboss.as.naming.NamingEventCoordinatorTestCase.testFireObjectEvent',
 'org.jboss.as.naming.NamingEventCoordinatorTestCase.testFireMultiLevelEvent',
 'org.jboss.as.naming.NamingEventCoordinatorTestCase.testFireAllEvent',
 'org.jboss.as.naming.NamingEventCoordinatorTestCase.testFireOneLevelEvent',
 'org.jboss.as.naming.ObjectFactoryTestCase.testBindAndRetrieveObjectFactoryFromInitialContext',
 'org.jboss.as.naming.ObjectFactoryTestCase.testBindAndRetrieveObjectFactoryFromNamingContext',
 'org.jboss.as.naming.ServiceBasedNamingStoreTestCase.testLookupBinding',
 'org.jboss.as.naming.ServiceBasedNamingStoreTestCase.testLookupNestedContext',
 'org.jboss.as.naming.ServiceBasedNamingStoreTestCase.testListBindings',
 'org.jboss.as.naming.ServiceBasedNamingStoreTestCase.testList',
 'org.jboss.as.naming.ServiceBasedNamingStoreTestCase.testLookupBindingUsingNestedContext',
 'org.jboss.as.naming.ServiceBasedNamingStoreTestCase.testStoredContext',
 'org.jboss.as.naming.ServiceBasedNamingStoreTestCase.testLookupBase',
 'org.jboss.as.naming.ServiceBasedNamingStoreTestCase.testLookupParentContext',
 'org.jboss.as.naming.subsystem.NamingSubsystemTestCase.testCompositeBindingOps',
 'org.jboss.as.naming.subsystem.NamingSubsystemTestCase.testOnlyExternalContextAllowsCache',
 'org.jboss.as.naming.subsystem.NamingSubsystemTestCase.testSchemaOfSubsystemTemplates',
 'org.jboss.as.naming.subsystem.NamingSubsystemTestCase.testCompositeBindingUpdate',
 'org.jboss.as.naming.subsystem.NamingSubsystemTestCase.testRejectionsEAP6',
 'org.jboss.as.naming.subsystem.NamingSubsystemTestCase.testRejectionsEAP7',
 'org.jboss.as.naming.subsystem.NamingSubsystemTestCase.testSubsystem',
 'org.jboss.as.naming.subsystem.NamingSubsystemTestCase.testSchema',
 'org.jboss.as.naming.WritableServiceBasedNamingStoreTestCase.testCreateSubcontext',
 'org.jboss.as.naming.WritableServiceBasedNamingStoreTestCase.testMultipleOwnersBindingReferences',
 'org.jboss.as.naming.WritableServiceBasedNamingStoreTestCase.testBind',
 'org.jboss.as.naming.WritableServiceBasedNamingStoreTestCase.testCreateSubContextNoOwner',
 'org.jboss.as.naming.WritableServiceBasedNamingStoreTestCase.testBindNested',
 'org.jboss.as.naming.WritableServiceBasedNamingStoreTestCase.testRebindNoOwner',
 'org.jboss.as.naming.WritableServiceBasedNamingStoreTestCase.testPermissions']

## Verify that all the files have the same values

In [ ]:
for path in dependency_files[:10]:
    with open(path, "r") as f:
        d = json.load(f)

    print(path)
    print(d.keys())
    print()

./scripts/minimized-files/naming/org.jboss.as.naming.WritableServiceBasedNamingStoreTestCase.testPermissions-c494a241f11c551779bc1904fa47348e-PASS-dependencies.json
dict_keys(['time', 'expectedRun', 'expected', 'dependentTest', 'polluters', 'hash', 'flakyClass'])

./scripts/minimized-files/cukes-http/lv.ctco.cukes.http.facade.HttpAssertionFacadeImplTest.shouldReturnBodyWhenEnabledAndNoMax-8cbc2d89d81d400bd1c61381f60a426a-FAILURE-dependencies.json
dict_keys(['time', 'expectedRun', 'expected', 'dependentTest', 'polluters', 'hash', 'flakyClass'])

./scripts/minimized-files/marine-api/net.sf.marineapi.ais.parser.AISMessageFactoryTest.testCreateWithTwo-64e87f61fe0dc7194d0c8be1eb266d7f-ERROR-dependencies.json
dict_keys(['time', 'expectedRun', 'expected', 'dependentTest', 'polluters', 'hash', 'flakyClass'])

./scripts/minimized-files/marine-api/net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testSequenceListenerWithIncorrectOrder-10be918b1171de27588c31d9a89823cd-ERROR-dependencies.json
dict_keys(['time', 'expectedRun', 'expected', 'dependentTest', 'polluters', 'hash', 'flakyClass'])

./scripts/minimized-files/elastic-job-lite-core/io.elasticjob.lite.internal.instance.ShutdownListenerManagerTest.assertIsShutdownAlready-f3c196681eb02fe87d6f88b4ff609ea7-ERROR-dependencies.json
dict_keys(['time', 'expectedRun', 'expected', 'dependentTest', 'polluters', 'hash', 'flakyClass'])

./scripts/minimized-files/lib/com.github.kevinsawicki.http.HttpRequestTest.postWithVaragsQueryParams-b9ce25cb22a453860a16b1588b971ca1-ERROR-dependencies.json
dict_keys(['time', 'expectedRun', 'expected', 'dependentTest', 'polluters', 'hash', 'flakyClass'])

## Dependency file for all 6 json files

In [ ]:
rows = []

for path in dependency_files:
    with open(path, "r") as f:
        d = json.load(f)

    rows.append({
        "dependent_test": d["dependentTest"],
        "flaky_class": d["flakyClass"],
        "expected_result": d["expected"],
        "num_polluters": len(d["polluters"]),
        "num_tests": len(d["expectedRun"]["testOrder"]),
        "elapsed_seconds": d["time"]["elapsedSeconds"]
    })

summary_df = pd.DataFrame(rows)

summary_df

,dependent_test,flaky_class,expected_result,num_polluters,num_tests,elapsed_seconds
0,org.jboss.as.naming.WritableServiceBasedNaming...,OD,PASS,1,70,383.478
1,lv.ctco.cukes.http.facade.HttpAssertionFacadeI...,OD,FAILURE,1,8,78.834
2,net.sf.marineapi.ais.parser.AISMessageFactoryT...,OD,ERROR,1,470,372.716
3,net.sf.marineapi.ais.event.AbstractAISMessageL...,OD,ERROR,1,236,394.492
4,io.elasticjob.lite.internal.instance.ShutdownL...,OD,ERROR,1,63,1320.964
5,com.github.kevinsawicki.http.HttpRequestTest.p...,OD,ERROR,1,149,138.111

## Check to see we have round0.json files that contain execution

In [ ]:
round_files = glob.glob(
    "**/detection-results/**/*.json",
    recursive=True
)

print("Detection result files:", len(round_files))

for f in round_files[:15]:
    print(f)

Detection result files: 0

Observed that the github repo doesn't included the json files with the results as well, and iDFlakies need to be run to gain this information.